name: Charmed MinIO

on:
  - push
  - pull_request

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - uses: balchua/microk8s-actions@v0.2.2
      with:
        addons: '["dns", "storage", "rbac"]'

    - name: Install dependencies
      run: |
        set -eux
        sudo snap install charm --classic
        sudo snap install juju --classic
        sudo snap install juju-wait --classic

    - name: Deploy MinIO
      run: |
        set -eux
        sg microk8s -c 'juju bootstrap microk8s uk8s'
        juju add-model minio
        charm build .
        juju deploy ~/charms/builds/minio/ \
            --config secret-key=foobar \
            --resource oci-image=minio/minio:RELEASE.2018-02-09T22-40-05Z
        juju wait -wvt 300

    - name: Test MinIO
      run: |
        set -eux
        kubectl run \
            --rm \
            -i \
            --restart=Never \
            --image=ubuntu \
            minio-check \
            -- \
            bash -c "apt update && apt install -y curl && curl -f http://minio.minio.svc.cluster.local:9000/"


    - name: Get pod statuses
      run: kubectl get all -A
      if: failure()

    - name: Get juju status
      run: juju status
      if: failure()

    - name: Get minio logs
      run: kubectl logs --tail 100 -nminio -ljuju-app=minio
      if: failure()

    - name: Get minio operator logs
      run: kubectl logs --tail 100 -nminio -ljuju-operator=minio
      if: failure()

